### ISSUE TITLE
再設計

### ISSUE THREAD

**Issue by nonick-mc** [nonick-js/bot#108]
* [ ] `interactions`フォルダを`commands`と`contexts`フォルダに分ける
* [x] すべての機能のリファクタリング・拡張性の向上
  * [x] 入退室メッセージ
  * [x] サーバー内通報
  * [x] イベントログ
  * [x] メッセージURL展開
  * [x] 自動認証レベル変更
  * [x] 自動アナウンス公開
  * [x] AutoMod Plus
  * [x] /timeout
  * [x] /embed
  * [x] /verify
  * [x] /firstmessage
  * [x] /bulkdelete
  * [x] /ratelimit
  * [x] /setting
  * [x] /info
  * [x] /help
* [x] DBの再設計
* [ ] AWSへの自動デプロイ
* [ ] ~~命名規則~~コーディングルールの再考

**Comment by nonick-mc** [comment]
(随時追加)
* `interactions`ファイルを`commands`と`contexts`に分離させる

**Comment by akki0256** [comment]
命名規則で参考にするサイト
https://google.github.io/styleguide/tsguide.html
